[package]
name = "ds3_decrypt"
version = "0.1.0"
edition = "2021"



[dependencies]
aes = "0.8.4"
cipher = "0.4.4"
hex-literal = "0.4.1"
cbc = {version = "0.1.2", features = ["block-padding"]}
phf = { version = "0.11.2", features = ["macros"] }
